# MLL Project Assignment

## Business Understanding

## Data understanding

## Data preparation

In [1]:
# imports

import time
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load the datasets
movies = pd.read_csv('datasets/movies-small/ml-latest-small/movies.csv', sep=',')
ratings = pd.read_csv('datasets/movies-small/ml-latest-small/ratings.csv', sep=',')

# Merging the datasets based on the movieId column
movie_ratings = pd.merge(ratings, movies, on='movieId')

# Display the first 5 rows of the merged dataset
movie_ratings.head(5)

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [7]:
movie_stats = ratings.groupby("movieId").agg(
    average_rating=("rating", "mean"),
    rating_count=("rating", "count")
).reset_index()

# Yhdistä keskiarvorating movies-datasettiin
movies_with_ratings = pd.merge(movies, movie_stats, on="movieId", how="left")

# Näytä ensimmäiset rivit
movies_with_ratings.head(10)

,movieId,title,genres,average_rating,rating_count
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3.920930,215.0
1,2,Jumanji (1995),Adventure|Children|Fantasy,3.431818,110.0
2,3,Grumpier Old Men (1995),Comedy|Romance,3.259615,52.0
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,2.357143,7.0
4,5,Father of the Bride Part II (1995),Comedy,3.071429,49.0
5,6,Heat (1995),Action|Crime|Thriller,3.946078,102.0
6,7,Sabrina (1995),Comedy|Romance,3.185185,54.0
7,8,Tom and Huck (1995),Adventure|Children,2.875000,8.0
8,9,Sudden Death (1995),Action,3.125000,16.0
9,10,GoldenEye (1995),Action|Adventure|Thriller,3.496212,132.0

## Modeling

## Evaluation

## Deployment