# MLL Project Assignment

## Business Understanding

## Data understanding

## Data preparation

In [18]:
# imports

import time
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In our project, we use the MovieLens dataset provided by GroupLens. Their website offers two versions of the dataset: one containing approximately 32 million movie ratings and another containing one hundred thousand (100,000) ratings intended for educational purposes. In this project, we use the dataset intended for educational use. The dataset consists of four main files: movies.csv, ratings.csv, links.csv and tags.csv. In this project we will use only two of these files: movies.csv and ratings.csv.

In [19]:
# Load the datasets
movies_org = pd.read_csv('datasets/movies-small/ml-latest-small/movies.csv', sep=',')
ratings_org = pd.read_csv('datasets/movies-small/ml-latest-small/ratings.csv', sep=',')

movies_org.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

The Movies.csv dataset contains information about the movies and includes three columns.
* MovieId: The unique identifier of the movie
* Title: The title of the movie
* genres: The genres associated with the movie

In [20]:
ratings_org.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

The rating.csv file contains the ratings given by users to movies. Each row in the dataset represents a singe rating given by a user to a specific movie. A single user can rate multiple movies, which means that userId may appear multiple times in the dataset.
* UserId: The unique identifier of the user
* movieId: The unique identifier of the movie
* rating: The rating given by the user
* timestamp: The time when the user submitted the rating

In [21]:
movies = movies_org.dropna(subset=["title", "genres"])
print("Originals movies dataset: ", len(movies_org))
print("Cleaned movies dataset: ", len(movies))

Originals movies dataset:  9742
Cleaned movies dataset:  9742

During the inspection of the movies.csv dataset, we observed that some rows may occasionally be parsed incorrectly by pandas. In such cases, pandas may merge the title and genres columns under the movieId column, which breaks the structure and integrity of the dataset. As a precautionary data-cleaning step, we remove these incorrectly parsed rows in the following code block. This ensures that the dataset maintains a consistent structure and that each column contains the correct type of information.

In [26]:
movies['genres'] = movies['genres'].str.split('|')
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]"
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]"
2,3,Grumpier Old Men (1995),"[Comedy, Romance]"
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]"
4,5,Father of the Bride Part II (1995),[Comedy]

In this step, we transform genres columns, which contains multiplse genres in a single string, separated by the pipe character ( | ), into a list of individual genres for each movie.

In [22]:
ratings = ratings_org[ratings_org["movieId"].isin(movies["movieId"])]

print("Original ratings: ", len(ratings_org))
print("Cleaned ratings: ", len(ratings))

Original ratings:  100836
Cleaned ratings:  100836

In the ratings.csv dataset, some ratings may refer to movies that are not present in the movies.csv dataset. To maintain data consistency, we filter the ratings and keep only those entries whose movieId exists in the movies dataset. These preprocessing steps improve data quality and ensure that the datasets can be reliably used in the analysis.

In [28]:
movie_stats = ratings.groupby("movieId").agg(
    average_rating=("rating", "mean"),
    rating_count=("rating", "count")
).reset_index()

movies_with_ratings = pd.merge(movies, movie_stats, on="movieId", how="left")

movies_with_ratings.head(10)

,movieId,title,genres,average_rating,rating_count
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]",3.920930,215.0
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]",3.431818,110.0
2,3,Grumpier Old Men (1995),"[Comedy, Romance]",3.259615,52.0
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]",2.357143,7.0
4,5,Father of the Bride Part II (1995),[Comedy],3.071429,49.0
5,6,Heat (1995),"[Action, Crime, Thriller]",3.946078,102.0
6,7,Sabrina (1995),"[Comedy, Romance]",3.185185,54.0
7,8,Tom and Huck (1995),"[Adventure, Children]",2.875000,8.0
8,9,Sudden Death (1995),[Action],3.125000,16.0
9,10,GoldenEye (1995),"[Action, Adventure, Thriller]",3.496212,132.0

In this code block, we merge the two datasets to enrich the movies dataset with rating information using pd.merge(). Specifically, we compute for each movie its average rating and the total number of ratings it has received from rating.csv dataset. Then, we merge this aggregated rating information with the movies dataset, creating a new dataframe movies_with_ratings that contains both movie metadata and their rating statistics.


This allow us to analyze movies not only by their details (Title, Genre) but also by their popularity and average ratings.

## Modeling

## Evaluation

## Deployment